name: mazar
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  get_it: ^7.7.0
  provider: ^6.1.2
  http: ^0.13.6
  shared_preferences: ^2.2.3
  photo_view: ^0.15.0
  dio: ^5.4.3+1
  image_picker: ^1.1.0
  pin_code_fields: ^8.0.1
  google_maps_flutter_web: ^0.5.6+2
  google_maps_flutter: ^2.6.1
  flutter_google_places: ^0.3.0
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  shimmer_animation: ^2.1.0+1
  url_launcher: ^6.2.6
  # firebase_core: ^2.30.0
  # firebase_messaging: ^14.8.2
  flutter_local_notifications: ^17.1.0
  path_provider: ^2.1.3
  connectivity: ^3.0.6
  #  carousel_slider: ^4.2.1
  carousel_slider: ^5.0.0
  fluro: ^2.0.5
  url_strategy: ^0.2.0
  universal_html: ^2.2.4
  flutter_widget_from_html_core: ^0.14.11
  #  phone_number: ^2.1.0
  country_code_picker: ^3.0.0
  flutter_typeahead: ^5.2.0
  flutter_inappwebview: ^6.0.0
  cached_network_image: ^3.3.1
  audioplayers: ^6.0.0
#  flutter_facebook_auth: ^6.0.4
#  google_sign_in: ^6.2.1
  expandable_bottom_sheet: ^1.1.1+1
  dotted_border: ^2.1.0
  share_plus: ^9.0.0
  scroll_to_index: ^3.0.1
  simple_speed_dial: ^0.1.7
#  sign_in_with_apple: ^6.1.0
#  firebase_auth: ^4.19.3
  flutter_svg: ^2.0.9
  flutter_xlider: ^3.5.0
#  firebase_crashlytics: ^3.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/
    - assets/language/
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700